### ISSUE TITLE
DTSU666 read value problem

### ISSUE THREAD

**Issue by folny** [serhmarch/ModbusTools#3]
Hello

I am trying this program to read values from the DSSU666 meter, but the values are not in the correct form. I have everything set up correctly and the format is set to float. I think the problem is in the format, you will probably have to add another float32 format.

DTSU666 manual https://www.deyeinverter.com/deyeinverter/2022/06/10/chintthreephase-instructionmanual-dt(s)su666-y0.464.1002v1.5190617.pdf

**Comment by serhmarch** [comment]
Hello
I guess your issue is your meter has non default 16 bit register order in 32 bit float value. You can easily change it adding new dataView item (or editing existing dataView item) using menu: Data->New Item(s)->Advanced tab, than choose Register order to "Most Signified First". 
If this do not help you can do the same but chaging Byte Order to "Most Signified First" as well.
![image](https://github.com/serhmarch/ModbusTools/assets/10882627/446c155a-8737-4673-ac60-ffd97e776d52)

**Comment by folny** [comment]
Thanks for the quick reply, the council helped and everything is fine now.

**Comment by serhmarch** [comment]
But it's better to do the following. 
Since your device most likely has the same order of 16-bit registers for 32-bit values, it is better to set this order in the device settings. And the default settings of DataViewItem are the same as those of the device to which they refer.
![image](https://github.com/serhmarch/ModbusTools/assets/10882627/944320af-fc73-4872-8a27-5bb3d5b51b54)
